export const ERROR_CODES = {
  // Client errors
  INVALID_REQUEST: 'INVALID_REQUEST',
  INVALID_URL: 'INVALID_URL',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',

  // Video errors
  VIDEO_NOT_FOUND: 'VIDEO_NOT_FOUND',
  AUDIO_TOO_LONG: 'AUDIO_TOO_LONG',
  TRANSCRIPT_TOO_LONG: 'TRANSCRIPT_TOO_LONG',

  // Article errors
  CRAWL_BLOCKED: 'CRAWL_BLOCKED',
  CRAWL_TIMEOUT: 'CRAWL_TIMEOUT',
  CONTENT_TOO_SHORT: 'CONTENT_TOO_SHORT',
  TEXT_TOO_LONG: 'TEXT_TOO_LONG',

  // AI/Service errors
  LLM_ERROR: 'LLM_ERROR',
  STT_ERROR: 'STT_ERROR',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
  CONFIGURATION_ERROR: 'CONFIGURATION_ERROR',

  // Server errors
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  ANALYSIS_FAILED: 'ANALYSIS_FAILED',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
